spring.datasource.url=jdbc:postgresql://localhost:5432/conecta-vida
spring.datasource.username=postgres
spring.datasource.password=cesmac
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8081